### Post Chronicler
POST http://localhost:8080/api/v1/chroniclers/c1
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "firstname": "Chat",
  "lastname": "GPT2.0",
  "isAi" : true
}
> {% client.global.set("cid", response.body) %}

### Get Chronicler
GET http://localhost:8080/api/v1/chroniclers/{{cid}}
Content-Type: application/json

### Post Storyteller 2

POST http://localhost:8080/api/v1/storytellers/
Content-Type: application/json

{
  "firstname": "Chris",
  "lastname": "Dufresne",
  "contactMethod": "phone",
  "preferredChronicler": { "id":  "{{cid}}"}
}
> {% client.global.set("sid", response.body) %}

### Get Storyteller
GET http://localhost:8080/api/v1/storytellers/{{sid}}

### Delete Chronicler
DELETE http://localhost:8080/api/v1/chroniclers/{{cid}}

### Delete Storyteller
DELETE http://localhost:8080/api/v1/storytellers/{{sid}}