### Create Storyteler
POST {{host}}/api/v1/storytellers/
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "firstname": "Chris",
  "lastname": "Dufresne",
  "contactMethod": "phone"
}
> {% client.global.set("sid", response.body) %}


### Create Question 1
POST {{host}}/api/v1/questions/
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "name": "Question 2",
  "text": "What is your favorite color?",
  "isCustom": true
}
> {% client.global.set("qid", response.body) %}

### Create Chronicler
POST {{host}}/api/v1/chroniclers/
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "firstname": "Chat",
  "lastname": "GPT2.0"
}
> {% client.global.set("cid", response.body) %}

### Post Interview 1 (We ignore Chronicler for now)
POST {{host}}/api/v1/interviews/storytellers/{{sid}}/chroniclers/{{cid}}
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "name": "Interview 3",
  "interviewQuestions": [
    {
      "id": "{{qid}}"
    }
  ]
}
> {% client.global.set("id", response.body) %}

### GET Interview
GET {{host}}/api/v1/interviews/{{id}}
Content-Type: application/json
Authorization: Bearer {{JWT}}

### Delete Question
DELETE {{host}}/api/v1/questions/{{qid}}
Authorization: Bearer {{JWT}}

### Delete Interview
DELETE {{host}}/api/v1/interviews/{{id}}
Authorization: Bearer {{JWT}}

### Delete Storyteller
DELETE {{host}}/api/v1/storytellers/{{sid}}
Authorization: Bearer {{JWT}}