### Create Storyteler
POST http://localhost:8080/storytellers/
Content-Type: application/json

{
  "firstname": "Chris",
  "lastname": "Dufresne",
  "contactMethod": "phone"
}
> {% client.global.set("sid", response.body) %}


### Create Question 1
POST http://localhost:8080/questions/
Content-Type: application/json

{
  "name": "Question 2",
  "text": "What is your favorite color?",
  "isCustom": true
}
> {% client.global.set("qid", response.body) %}

### Create Chronicler
POST http://localhost:8080/chroniclers/
Content-Type: application/json

{
  "firstname": "Chat",
  "lastname": "GPT2.0"
}
> {% client.global.set("cid", response.body) %}

### Post Interview 1 (We ignore Chronicler for now)
POST http://localhost:8080/interviews/storytellers/{{sid}}/chroniclers/{{cid}}
Content-Type: application/json

{
  "name": "Interview 3",
  "interviewQuestions": [
    {
      "id": "{{qid}}"
    }
  ]
}
> {% client.global.set("id", response.body) %}

### GET Interview
GET http://localhost:8080/interviews/{{id}}
Content-Type: application/json

###Schedule an interview
POST http://localhost:8080/interviews/storytellers/{{sid}}/scheduled/{{id}}?time=2023-06-08T12%3A34%3A00Z

### GET Next Scheduled Interview
GET http://localhost:8080/interviews/storytellers/{{sid}}/scheduled:next/

### GET All Scheduled Interview
GET http://localhost:8080/interviews/storytellers/{{sid}}/scheduled:all/

### Delete Scheduled Interview
DELETE http://localhost:8080/interviews/scheduled/5f5ztgjyj

### Delete Question
DELETE http://localhost:8080/questions/{{qid}}

### Delete Interview
DELETE http://localhost:8080/interviews/{{id}}

### Delete Storyteller
DELETE http://localhost:8080/storytellers/{{sid}}