//AddPipe Callback tests
#### AddPipe Callback Create Storyteler
POST http://localhost:8080/api/v1/storytellers/
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "firstname": "Chris",
  "lastname": "Dufresne",
  "contactMethod": "phone"
}
> {% client.global.set("sid", response.body) %}

### AddPipe Callback Create Question 1
POST http://localhost:8080/api/v1/questions/
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "name": "Question 2",
  "text": "What is your favorite color?",
  "isCustom": true
}
> {% client.global.set("qid", response.body) %}

### AddPipe Callback Create Chronicler
POST http://localhost:8080/api/v1/chroniclers/c1
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "firstname": "Chat",
  "lastname": "GPT2.0",
  "isAi" : true
}
> {% client.global.set("cid", response.body) %}

### AddPipe Callback Post Interview 1
POST http://localhost:8080/api/v1/interviews/storytellers/{{sid}}/chroniclers/{{cid}}
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "name": "Interview 3",
  "interviewQuestions": [
    {
      "id": "{{qid}}"
    }
  ]
}
> {% client.global.set("id", response.body) %}

#### GET Interview
GET http://localhost:8080/api/v1/interviews/{{id}}
Content-Type: application/json

> {% client.global.set("iqid", response.body.interviewQuestions[0].id) %}

### AddPipe Callback
POST http://localhost:8080/api/v1/media/
Content-Type: application/json
Authorization: Bearer {{JWT}}
X-Pipe-Signature: lXvRNKamkr/K04l61ICpwVAxD0w=

{
  "version":"1.0",
  "event":"video_copied_pipe_s3",
  "data":{
    "storedStatus":"stored successful",
    "videoName":"STREAM_NAME",
    "size":194373,
    "checksum_md5":"968302a32f7c7ed67523274aa8a92717",
    "checksum_sha1":"b733ec235ea57119172c8b044220e793446063fe",
    "id":123,
    "url":"https://addpipevideos.s3.amazonaws.com/b8e2f5bfd04a93b434bd8c740bff744d/STREAM_NAME.mp4",
    "rawRecordingUrl":"https://addpipevideos.s3.amazonaws.com/b8e2f5bfd04a93b434bd8c740bff744d/STREAM_NAME_raw.EXTENSION",
    "snapshotUrl":"https://addpipevideos.s3.amazonaws.com/b8e2f5bfd04a93b434bd8c740bff744d/STREAM_NAME.jpg",
    "filmstripUrl":"https://addpipevideos.s3.amazonaws.com/b8e2f5bfd04a93b434bd8c740bff744d/STREAM_NAME_filmstrip.jpg",
    "cdn":{"cdnRecordingUrl":"https://recordings-eu.addpipe.com/b8e2f5bfd04a93b434bd8c740bff744d/STREAM_NAME.mp4",
      "cdnRawRecordingUrl":"https://recordings-eu.addpipe.com/b8e2f5bfd04a93b434bd8c740bff744d/STREAM_NAME_raw.EXTENSION",
      "cdnSnapshotUrl":"https://recordings-eu.addpipe.com/b8e2f5bfd04a93b434bd8c740bff744d/STREAM_NAME.jpg",
      "cdnFilmstripUrl":"https://recordings-eu.addpipe.com/b8e2f5bfd04a93b434bd8c740bff744d/STREAM_NAME_filmstrip.jpg"},
    "bucket":"eu1-addpipe",
    "region":"eu-central-1",
    "payload":"{\"interview_question_id\":\"{{iqid}}\"}"
  }
}

> {% client.global.set("mid", response.body) %}


### Find Media By Storyteler
GET http://localhost:8080/api/v1/media/storytellers/{{sid}}
Content-Type: application/json
Authorization: Bearer {{JWT}}
