### Post Org 1
POST {{host}}/api/v1/organizations/
Content-Type: application/json

{
  "name": "Organization 1"
}
> {% client.global.set("oid", response.body.id) %}

### Get Org
GET {{host}}/api/v1/organizations/{{oid}}
