### Post Question 1
POST {{host}}/api/v1/questions/
Content-Type: application/json

{
  "name": "Question 1",
  "text": "What is your favorite color?",
  "isCustom": true
}
> {% client.global.set("id", response.body) %}

### GET Question
GET {{host}}/api/v1/questions/{{id}}
Content-Type: application/json

### Update Question
PUT {{host}}/api/v1/questions/{{id}}
Content-Type: application/json

{
  "name": "Question 1",
  "text": "What is your favorite color?",
  "isCustom": false
}

### Get All questions
GET  {{host}}/api/v1/questions/
Content-Type: application/json
Authorization: "Bearer {JWT}"

