### Health
GET {{host}}/api/v1/health/

### Post Storyteller

POST {{host}}/api/v1/storytellers/
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "firstname": "Chris",
  "lastname": "Dufresne",
  "contactMethod": "phone"
}
> {% client.global.set("cid", response.body) %}

### PUT (Update) Storyteller 2
PUT {{host}}/api/v1/storytellers/
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
"id": "{{cid}}",
"firstname": "Christopher",
"lastname": "Dufresne",
"contactMethod": "text",
"mobile": "123-123-1234",
"email": "test@test.com",
"preferredTimes": [{"time": "15:01:00", "dayOfWeek": "SATURDAY"}],
"onboardingStatus": "ONBOARDING_STARTED"
}

### Get the Storyteller
GET {{host}}/api/v1/storytellers/d1
Authorization: Bearer {{JWT}}

### Delete the Storyteller
DELETE {{host}}/api/v1/storytellers/{{cid}}



### AWS Tests
GET https://pb5a9nhpcb.us-east-1.awsapprunner.com/health/

### Post Storyteller
POST https://pb5a9nhpcb.us-east-1.awsapprunner.com/storytellers/
Content-Type: application/json

{
  "firstname": "Chris",
  "lastname": "Dufresne",
  "contactMethod": "phone"
}
> {% client.global.set("cid", response.body) %}

### PUT (Update) Storyteller 2
PUT https://pb5a9nhpcb.us-east-1.awsapprunner.com/storytellers/
Content-Type: application/json

{
"id": "{{cid}}",
"firstname": "Christopher",
"lastname": "Dufresne",
"contactMethod": "text",
"mobile": "123-123-1234",
"email": "test@test.com",
"preferredTimes": [{"time": "15:01:00", "dayOfWeek": "SATURDAY"}],
"onboardingStatus": "ONBOARDING_STARTED"
}

### Get the Storyteller
GET https://pb5a9nhpcb.us-east-1.awsapprunner.com/storytellers/{{cid}}
