### Health
GET http://localhost:8080/

### Post Storyteller

POST http://localhost:8080/storytellers/
Content-Type: application/json

{
  "firstname": "Chris",
  "lastname": "Dufresne",
  "contactMethod": "phone"
}
> {% client.global.set("cid", response.body) %}

### PUT (Update) Storyteller 2
PUT http://localhost:8080/storytellers/
Content-Type: application/json

{
"id": "{{cid}}",
"firstname": "Christopher",
"lastname": "Dufresne",
"contactMethod": "text"
}

### Get the Storyteller
GET http://localhost:8080/storytellers/{{cid}}

### Delete the Storyteller
DELETE http://localhost:8080/storytellers/{{cid}}



### AWS Tests
GET https://pb5a9nhpcb.us-east-1.awsapprunner.com/health

### Get all the Storytellers
GET https://pb5a9nhpcb.us-east-1.awsapprunner.com/storytellers/
# Comes back empty

### Post Storyteller 2
POST https://pb5a9nhpcb.us-east-1.awsapprunner.com/storytellers/
Content-Type: application/json

{
  "name": "Chris",
  "contactMethod": "phone"
}

### Get all the Storytellers
GET https://pb5a9nhpcb.us-east-1.awsapprunner.com/storytellers/
# Returns one storyteller (me)
# Grab the id that is returned and paste it below

### Update Storyteller
PUT https://pb5a9nhpcb.us-east-1.awsapprunner.com/storytellers/
Content-Type: application/json

{
  "id" : "{Paste the ID Here}",
  "name": "Christopher",
  "contactMethod": "text"
}

### Get all the Storytellers
GET https://pb5a9nhpcb.us-east-1.awsapprunner.com/storytellers/
# Returns the updated storyteller

### Delete all Storytellers
DELETE https://pb5a9nhpcb.us-east-1.awsapprunner.com/storytellers/all