### Health
GET http://localhost:8080/

### Post Storyteller 1
POST http://localhost:8080/storytellers/
Content-Type: application/json

{
  "name": "Tom"
}

### Post Storyteller 2

POST http://localhost:8080/storytellers/
Content-Type: application/json

{
  "firstname": "Chris",
  "lastname": "Dufresne",
  "contactMethod": "phone"
}

### PUT (Update) Storyteller 2
PUT http://localhost:8080/storytellers/
Content-Type: application/json

{
"id": "807d3571-4853-408d-8935-d8e88c08a234",
"name": "Chris",
"contactMethod": "text"
}

### Post Storyteller 3

POST http://localhost:8080/storytellers/
Content-Type: application/json

{
  "name": "Carlos"
}

### Update Storyteller 2
PUT http://localhost:8080/storytellers/
Content-Type: application/json

{
  "id" : "86386737-fcf0-416d-8074-a140b992e27a",
  "name": "Christopher"
}

### Get all the Storytellers
GET http://localhost:8080/storytellers/

### Delete all Storytellers
DELETE http://localhost:8080/storytellers/all

### AWS Tests
GET https://pb5a9nhpcb.us-east-1.awsapprunner.com/health

### Get all the Storytellers
GET https://pb5a9nhpcb.us-east-1.awsapprunner.com/storytellers/
# Comes back empty

### Post Storyteller 2
POST https://pb5a9nhpcb.us-east-1.awsapprunner.com/storytellers/
Content-Type: application/json

{
  "name": "Chris",
  "contactMethod": "phone"
}

### Get all the Storytellers
GET https://pb5a9nhpcb.us-east-1.awsapprunner.com/storytellers/
# Returns one storyteller (me)
# Grab the id that is returned and paste it below

### Update Storyteller
PUT https://pb5a9nhpcb.us-east-1.awsapprunner.com/storytellers/
Content-Type: application/json

{
  "id" : "{Paste the ID Here}",
  "name": "Christopher",
  "contactMethod": "text"
}

### Get all the Storytellers
GET https://pb5a9nhpcb.us-east-1.awsapprunner.com/storytellers/
# Returns the updated storyteller

### Delete all Storytellers
DELETE https://pb5a9nhpcb.us-east-1.awsapprunner.com/storytellers/all